---
title: "Proposal"
author: "Yan Wang"
date: "2024-02-21"
output: pdf_document
bibliography: ./Self-Concept Clarity and Well-Being.bib
---

## Exploring the Role of Deviance on Self-Concept Clarity Across the Lifespan

Self-concept clarity means a clear and certain understanding of oneself and is usually associated with positive feelings about the self [@campbellSelfconceptClarityMeasurement1996; @campbellSelfesteemClaritySelfconcept1990] . In research on the self, self-concept clarity is one of the concepts associated closely with well-being [@campbellStructureSelfConceptIts2003]. Recently, a curvilinear relationship has been found on self-concept clarity over time [@lodi-smithGettingKnowMe2010]. Yet, the underlying mechanism for this relationship stays unclear. This study aims to test a potential explanation for the relationship between self-concept clarity and subjective well-being.

## Self-concept Clarity and Well-being

Researchers have found positive relationships between self-concept clarity and subjective well-being, emotional stability, resilience, and physical health; as well as negative relationships between self-concept clarity and negative affect, including anxiety and depression [@campbellSelfconceptClarityMeasurement1996; @campbellStructureSelfConceptIts2003; @lightSelfConceptClaritySelfRegulation2017; @ritchieSelfconceptClarityMediates2011;@lightInsOutsSelf2013;@stopaConstructingSelfRole2010]. Research also suggests that well-being factors can influence self-concept clarity: better well-being, especially physical health, relation stability, and role stability, is also associated with higher self-concept clarity, [@carterExaminingRelationshipSelfPerceptions2019; @slotterAllRoleTransitions2017]. It is notable that both well-being and self-concept clarity change with age.

## Self-Concept Clarity and Age
Despite the past assumption of a positive association between self-concept clarity and age, @lodi-smithGettingKnowMe2010 found a reverse U-shaped curvilinear relationship between the two variables across lifespan. But why the relationship between the two variables changes over time?
One potential explanation is social role. The entrance of a social role might add to self-concept therefore increasing self-concept clarity [@lightInsOutsSelf2013]. In contrast, the exit from a social role, especially when an individual is unprepared for the exit, may lead to a decrease in self-concept clarity [@lightInsOutsSelf2013]. When people are in emerging adulthood, even though they might exit their role as a student, they have other roles like employees, partnerships, parents, etc. to enter. For middle-aged people, their role entrance opportunities are more restricted than young adults and they might exit their roles as parents or children. However, generally speaking, their social roles are relatively stable and middle-aged adults are able to obtain and maintain social roles. Later adulthood is when social role exits start to rise. For example, retirement and independence of children can both lead to role exit. Without the cognitive attribution of pairing a role exit with entering a new role, the effect of role exit on self-concept clarity is associated with a drop in self-concept clarity [@lightInsOutsSelf2013]. 
In Light, in her -@lightUnpublishedData2024 unpublished data, they find a more specified interactive variable, the importance of self-concept clarity to subjective well-being, showing the same pattern as @lodi-smithGettingKnowMe2010's finding. Specifically, when the slope representing the effect of self-concept clarity on subjective well-being is on y-axis and age is on x-axis, the curve rises from emerging adult to middle age and drops in elderly adulthood, thus forming a reversed U-shape [@lightUnpublishedData2024].
<!--
Well-being and Age
Another element to consider when asking why the relationship between self-concept clarity and well-being is curvilinear across the lifespan is the relationship between well-being and age. This topic is not only studied by psychologists but also by economists with parallel theories (López et al., 2013). Interestingly, not a cohesive conclusion has been made in both fields regarding what the shape of the slope is between well-being and age. The mixed result of linear, unchanging, U-shaped, and reversed U-shaped has been proposed and supported by different research in both fields (López et al., 2013). At this moment, U-shaped seems to be the most popular and accepted result in which well-being drops around middle age and rises back up during elderhood. According to the social roles’ influence above, it can be that although middle-aged adults have many stable social roles, not all of the roles are desirable, therefore having a lower overall well-being. However, most variations of the ongoing debate emerge in the data of more elderly adults (Blanchflower, 2021).
At the same time, social roles can be seen as part of the social norms, and social norms change for people at difference ages. Therefore, social roles may not be the full explanation for the found mechanism. In turn, I would like to propose social norms or social clock as an alternative explanation for this underlying mechanism for it is a more inclusive and holistic factor.
Deviance and Well-being
Social clock consists of major life events happening within a normative age range (Helson et al. 1984). Social clock theory states that being on-time has a positive association with well-being, whereas being off-time has a negative association to well-being (Helson et al. 1984; Neugarten 1979). It is commonly believed that being either early or late for major life-events can be stressful and leads to less social support. 
Rook et al. (1989) found that people who are late for a desirable life-event experience psychological distress but not people who are early. However, more current studies have found that individuals experience distress when experiencing life-events early (Pekel-Uludağlı & Akbaş, 2019; Abrams et al., 2021). For younger adults, Pekel-Uludağlı and Akbaş (2019) found that people who perceived themselves as getting married and having children earlier than their peers experienced higher level of depression and lower level of need satisfaction. Their results support the social clock theory because people who perceived themselves as married on-time had higher life satisfaction and need satisfaction compared to both people who perceived themselves as late or early. Similarly, Abrams et al. (2021) found that elderly adults who leave jobs unexpectedly have an increased risk of experiencing depressive symptoms. It is important to note that the perception of being off-time is often subjective in these study for the statistical average for life-events changes across generations.
Even though major life-events are about the same in a society, people from different age-groups might prioritize different concepts (Arnett, 2001). For example, middle-aged people consider physical transition less important than emerging adults (Arnett, 2001). Therefore, the perceived importance of norms might influence people’s perception on their self-concept, which in turn, may act as a mediator for the relationship between self-concept clarity and subjective well-being. In contrast, the perceived flexibility of norms at various life stages may moderate the strength of the relationship between self-concept clarity and subjective well-being. In other words, the extent to which people deviate from the social clock might be related to both their self-concept clarity and their well-being.
Current Study
How can the role of deviance from the social clock explain the curvilinear relationship between self-concept clarity and subjective well-being? 
In this thesis, I intend to argue that 1) perceived deviance from the social clock will be associated with lower subjective well-being, 2) lower self-concept clarity will be associated with lower subjective well-being, 3) perceived deviance from the social clock will mediate the association between self-concept clarity and subjective well-being, 4) perceived flexibility of the social clock will moderate the relationship between perceived deviance from the social clock and subjective well-being, 5) age will moderate the relationship between self-concept clarity & subjective well-being, and perceived deviance from the social clock & self-concept clarity.
-->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("papaja")
r_refs("r-references.bib")
```
